= Introduction

== Foodborne disease and the Danish smiley scheme

Foodborne disease remains a substantial public-health burden. The World Health Organization estimates that contaminated food sickens 600 million people each year and causes 420,000 deaths @who2015foodborne. Most cases are caused by enteric bacteria, viruses, and parasites. In US restaurant norovirus outbreaks, food workers and food-handling practices account for the largest share of identified contributing factors @holst2025contributing. The same pattern shows up in Denmark, where outbreak investigations repeatedly identify ill kitchen staff and healthy carriers among employees as the leading factor in restaurant norovirus outbreaks @dtu2024zoonoses. 

National regulators respond by inspecting food-serving premises on a recurring, risk-tiered schedule @fda2022foodcode @foedevarestyrelsen_bekendtgoerelse. Denmark introduced a national smiley scheme in 2001 along these lines. After each inspection, the establishment receives one of three faces. A happy face marks an inspection with no remarks. A neutral face marks a written instruction to correct a specific breach. A sad face marks more serious enforcement outcomes, including orders, bans, administrative fines, and police referrals @foedevarestyrelsen_findsmiley. The most recent smiley must be posted at the entrance, and the outcomes of the last four visits to an establishment are kept in an open national register @bavorova2012compliant. Evidence from the Los Angeles food inspection system shows that such schemes change both consumer demand and operator behaviour #cite(<jin2003effect>, form: "prose"). The same paper estimated a roughly 20% drop in food-related-illness hospitalisations after introduction, although a later re-analysis using a longer pre-treatment window contents this result @ho2019newevidence.

== The inspection planning gap

Public posting only works if food inspections happen often enough to keep the displayed smiley meaningful. Danish food inspections run on a risk-based schedule set by Fødevarestyrelsen, with restaurants in the typical risk group inspected approximately once a year and higher-risk premises more often @foedevarestyrelsen_bekendtgoerelse @foedevarestyrelsen_kontrolfrekvens. Any non-happy smiley triggers a shorter follow-up interval until the food establishment recovers a happy smiley. Outside the regular schedule, a customer can report hygiene problems to Fødevarestyrelsen through its public complaint channel, and such a complaint can trigger an off-schedule inspection @foedevarestyrelsen_klage. 

The displayed smiley indicates the last inspection, not the restaurant's current state, and the complaint route depends on a diner writing to Fødevarestyrelsen, which most diners with a poor experience do not do. The health agency planner cannot tell which currently-compliant restaurants are most at risk of failing the next inspection.

== Reviews as a hygiene signal

Online review platforms cover a large share of restaurants in developed markets, and Google Maps in particular has been used for nationwide restaurant-level analysis in European settings @starakiewicz2025predicting @hering2025hygienecasting. Most diners who report an illness in online reviews never file a corresponding regulatory complaint. In the only published direct comparison we are aware of, only 3% of the food-related-illness episodes described in Yelp reviews of New York City restaurants had a matching record in the city's complaint system @harrison2014using.

Yelp-based classifiers reported binary accuracy of 82% on a curated subset of 612 inspections using the Seattle health register @kang2013whereeat, 78% on a set of 440 Chinese restaurants in San Francisco @schomberg2016supplementing, and over 90% with machine-learning on data from Kitchener-Waterloo @wong2016predicting. Two US cities have used review-derived signals operationally. New York City has run a deployed complaint screening classifier since 2012 that flags Yelp reviews describing illness symptoms and has supported the identification of ten outbreaks and 8,523 reports @effland2018discovering, and the Boston tournament organised by #cite(<glaeser2016crowdsourcing>, form: "prose") produced out-of-sample algorithms that performed comparably to expert inspection targeting.

Other work has probed specific aspects of the review signal. #cite(<mejia2019moralhazard>, form: "prose") used review signals to identify hygiene deterioration in around 30% of New York City restaurants within 90 days of a certifying inspection. #cite(<siering2021leveraging>, form: "prose") combined sentiment polarity with word features and reached a macro F1 of 0.82, while finding a disconfirmed expectancy bias in negative reviews, where hygiene problems are flagged less often when they fit an already-negative overall impression. Across four US cities, #cite(<jeon2023predicting>, form: "prose") found that six of eight emotion dimensions, including disgust and anger, were significant predictors of an upcoming hygiene rating, alongside review-volume and readability features.

#cite(<altenburger2019yelp>, form: "prose") re-ran the Seattle analysis on the full 13,299-inspection register from which the 612 inspections used by #cite(<kang2013whereeat>, form: "prose") were drawn, and found that Yelp features had lower predictive power than prior inspection history and added nothing significant once that history was in the model. The simple star rating correlates with sanitation only within chain restaurants @park2016yelp, and a recent study of New York City's deployed review classifier reports minimal correlation at the neighbourhood level between its review-level signals and inspection outcomes @shaveet2025foodborne. #cite(<farronato2025consumerreviews>, form: "prose") showed that reviews are more informative about hygiene dimensions a diner can directly observe (food temperature, pests) than about workers' hygiene and facilities maintenance.

In Germany, #cite(<hering2025hygienecasting>, form: "prose") paired Google Maps reviews with hygiene-incident reports scraped from federal-state publication portals and trained an XGBoost classifier on word-frequency and review-engagement features, reaching a macro F1 of 0.87 on a test set in which the positive class contained only 175 food establishments. Across the literature, whether any review-derived signal is strong enough for an inspector to act on depends on city, restaurant type, label construction, and choice of prediction target. The high accuracy numbers from early US studies do not hold up under more demanding evaluation, including the only full-register replication @altenburger2019yelp.

== This work

The Danish setting allows a clean test of these questions on a national regulatory target. The smiley register covers the full population of Danish food establishments and is updated on the regulator's risk-tiered schedule, so a model can be trained and evaluated against the same outcome the regulator records. This is closer in structure to the Seattle full register @altenburger2019yelp than to the curated subsets that produced the earlier US accuracy numbers @kang2013whereeat. Google Maps has broad coverage of Danish restaurants, and the two sources can be linked using only public data.

A working predictor would let Fødevarestyrelsen prioritise off-schedule visits to currently-compliant restaurants that the regular schedule has no reason to act on. It would give complaint-triage staff a second source of information to set against an isolated complaint. This paper tests whether the signal in those reviews is strong enough to support either use. The test is run on a national inspection register, with the smiley as the prediction target and a ranking framing under a fixed inspection budget. 
